### ISSUE TITLE
Upgrade to RavenDB 3

### ISSUE THREAD

**Issue by vincentlabatut** [JudahGabriel/RavenDB.AspNet.Identity#8]
Hi,
I've upgraded to RavenDB 3 and it compiles well.
  <package id="Microsoft.AspNet.Identity.Core" version="2.1.0" targetFramework="net45" />
  <package id="RavenDB.Client" version="3.0.3528" targetFramework="net45" />

However, when I run a simple ASP.NET 5 MVC web site, having followed you instructions, I get some problems. The users are not persisted in the store.
I had to call this.session.SaveChanges();  in the CreateAsync method of the UserStore class.
I guess I missed something. I'm using RavenDB Embedded.

By the way, how do you make the calls to RavenDB "Store" persistent? I provide a RavenDB open session to the usermanager, who should call savechanges and dispose the session?
Isn't there a paradigm problem here?

There is a problem in the ASP.NET web site too, it create a instance of User with only a Name (no Id) at registration, and your provider doesn't fill automatically the Id from the Name. We can easily fix the AccountController to do that. 
I would not do that in real life, but the ASP.NET MVC5 "Demo" does not work as is with 

These are not big deals, but it did not work as simply as the tutorial. Great piece of code, very useful, thanks.

**Comment by JudahGabriel** [comment]
That's by design. It doesn't call .SaveChanges, because you may want control over that. 

The way we do it in our apps is, have a RavenDbController base class for all your controllers. Inside that, create a document session and when the action completes, call SaveChanges. Check out the [RavenDB MVC Starter Kit](https://github.com/JudahGabriel/RavenDB.ModernMvcStarterKit) for an example how this works.
